### ISSUE TITLE
Infinite loop when triggering Deep Nav

### ISSUE THREAD

**Issue by dvargasfuertes** [paulovieira/roam-reference-path#17]
Hey,

When a user has both Deep Nav and this extension enabled, and triggers Deep Nav, it causes an infinite loop in this extension.

https://user-images.githubusercontent.com/7143571/200952321-1fa03311-ec91-4a13-87cf-cb70dd0f55e8.mp4

I have confirmed that it is this code block that gets stuck: https://github.com/paulovieira/roam-reference-path/blob/main/extension.js#L728-L834

Let me know if you need any help diagnosing!

**Comment by paulovieira** [comment]
Thanks for the detailed report! The logic in the loop was indeed very weak. The problem was caused by Deep Nav adding a `div.roam_navigator_hint` and roam-reference-path not expecting it. This is now corrected. The following was done:

- roam-reference-path will still try to find the elements via `.parentElement` and `.firstElementChild` as before (optimized case); but if they are not found in the expected place (which might happen when other extensions mutate the DOM, such as Workbench/DeepNav), it will try again using `.closest()` and `.querySelector()`; this solves the current issue;
- a hard limit of 99 iterations for the main loop was also added; if some other problem arises in the future, the infinite loop problem will not happen again
